### ISSUE TITLE
Database sharing and access control

### ISSUE THREAD

**Issue by marcua** [marcua/ayb#281]
# Rough description
A database owner should be able to allow other users/entities to have following levels of access
- read-only access
- read/write access 
- manager (to be able to control sharing with anyone except the owner)

A database owner should also be able to control whether the public can have various forms of read-only access
- metadata only
- forking
- read-only querying

# The plan
- [x] Introduce SQL data model (#461) and Rust data model to mirror it (#466).
- [x] Add endpoint to support updates to a database's public sharing level. Make this a generic update_database endpoint.
  - [x] #473
  - [x] Support for read-only queries and listing databases (#479)
- [x] Add endpoint to add / update an entity's access to a database. Setting to `no_access` removes the row if it exists. Permissions: must be manager or owner, managers can't change owner permissions. (#487)
- [x] Documentation (#483)

**Comment by sofiaritz** [comment]
I think we should combine forking and querying, if someone can fork the database then they can run read-only queries as well :)

**Comment by marcua** [comment]
Definitely before we have forking support and support for varying memory/CPU for different databases, I agree. :)

The reason I was thinking someone might want to give fork read-only access but not query read-only access is because queries take up resources on your running database, whereas forking doesn't. So perhaps in the future when you want someone to look at your dataset but don't want them to use up your CPU running queries, you can say "fork my dataset and let me know what you find!" without having to worry about beefing up your own running database.

Definitely not something we have to worry about for a while :).

**Comment by marcua** [comment]
Working on this next! Came up with a rough outline of a plan in the issue description!

**Comment by marcua** [comment]
SQLite data models work, and started on Rust data models. For next time
* Add instructions on setting up postgres for testing to readme. need `createuser -P postgres_user` (enter password `test`) and (still to figure out) some way to run `sudo -u postgres psql -c "alter user postgres_user createdb;"` (there's a `psotgres` user on ubuntu, not on MacOS) 
* on `permissions-datamodels` branch, fix whatever the postgres issue is after getting installation working
* continue developing on `permissions-rustdatamodels`

**Comment by marcua** [comment]
* Updated Linux-vs-Mac instructions with #463
* Merged #461
* Continuing on `permissions-rustdatamodels`!

**Comment by marcua** [comment]
Done
* `permissions-rustdatamodels` now has the data models
* fields on existing database CRUD queries handle `public_sharing_level`
* client and server handle public sharing level on database creation

Next
* Database support for updating `public_sharing_level`
* Database support for create/update/remove `entity_database_permission`

**Comment by marcua** [comment]
Reworked plan to be endpoint-focused (e.g., expose public sharing first) rather than layer-focused (e.g., implementing all DB functionality first, but no endpoints are exposed).

First up: Add endpoint to support updates to a database's public sharing level. Make this a generic update_database endpoint. Permissions: must be manager or owner.

**Comment by marcua** [comment]
Almost done with endpoint to update public sharing level.

Next
* Finish update public sharing level
* Fix issue for update_profile and update_database where no arguments results in a SQL syntax error
* CRUD support for entity_database_permission

**Comment by marcua** [comment]
Server-side support for public sharing level updates done. Started writing end-to-end tests.

Next
* Add client-side support, merge
* Finish writing tests for public sharing endpoint and permissions
* Support read-only

**Comment by marcua** [comment]
`public_sharing_level is now updateable! Next up:
* Support read-only
* Support listing database

**Comment by marcua** [comment]
List and query logic and tests are all set (exposed to the query and entity details endpoints, passed through properly to rusqlite). Next
* Clean up some debugging I did to figure out correct SQLite flags `(SQLITE_OPEN_CREATE` should only co-exist with `SQLITE_OPEN_READ_WRITE)`
* Catch "executing write on read-only query" from rusqlite and pass it to client properly
* Update tests with appropriate error from previous bullet

**Comment by marcua** [comment]
Merged working support for fork/read-only public sharing level!

Next
* Documentation
* Version bump
* CRUD for entity-level access to database

**Comment by marcua** [comment]
Wrote up documentation for both public sharing level and entity-level permissions. Next
* CRUD for entity-level access to database
* Endpoint to call that CRUD
* Update permissions logic to look up entity-level permissions

**Comment by marcua** [comment]
Database-/endpoint-/CLI-level support for sharing is implemented (but untested) on branch `permissions-crud`. Next
* Update permissions logic for read-only/read-write permissions
* Update permissions logic for managers
* Add tests (query levels, management permissions, ensure owners are protected)

**Comment by marcua** [comment]
Permissions work and are covered by end-to-end tests! (And tests helped discover a bug, yay!). To ship:
* Code review
* Consider whether to call the endpoint `entity_database_permissions` or `share`
* Add one more test that a second database owned by first entity isn't accessible to second entity despite second entity having access to first database.

**Comment by marcua** [comment]
All done and merged! Next steps:
* Test the documentation, and if it works, merge
* Version bump and announce!!!!!
